# Capstone Project - The Battle of Neighborhoods (Week 1-2)

## Business Problem section

#### Background

According to Bloomberg News, the London Housing Market is in a rut. It is now facing a number of different headwinds, including the prospect of higher taxes and a warning from the Bank of England that U.K. home values could fall as much as 30 percent in the event of a disorderly exit from the European Union. More specifically, four overlooked cracks suggest that the London market may be in worse shape than many realize: hidden price falls, record-low sales, homebuilder exodus and tax hikes addressing overseas buyers of homes in England and Wales. 

#### Business Problem

In this scenario, it is urgent to adopt machine learning tools in order to assist homebuyers clientele in London to make wise and effective decisions. As a result, the business problem we are currently posing is: how could we provide support to homebuyers clientele in to purchase a suitable real estate in London in this uncertain economic and financial scenario? 

To solve this business problem, we are going to cluster London neighborhoods in order to recommend venues and the current average price of real estate where homebuyers can make a real estate investment. We will recommend profitable venues according to amenities and essential facilities surrounding such venues i.e. elementary schools, high schools, hospitals & grocery stores.

##  Data section

Data on London properties and the relative price paid data were extracted from the HM Land Registry (http://landregistry.data.gov.uk/). The following fields comprise the address data included in Price Paid Data: Postcode; PAON Primary Addressable Object Name. Typically the house number or name; SAON Secondary Addressable Object Name. If there is a sub-building, for example, the building is divided into flats, there will be a SAON; Street; Locality; Town/City; District; County.

To explore and target recommended locations across different venues according to the presence of amenities and essential facilities, we will access data through FourSquare API interface and arrange them as a dataframe for visualization. By merging data on London properties and the relative price paid data from the HM Land Registry and data on amenities and essential facilities surrounding such properties from FourSquare API interface, we will be able to recommend profitable real estate investments.

##Â Methodology section

The Methodology section will describe the main components of our analysis and predication system.
The Methodology section comprises four stages: 
    1. Collect Inspection Data
    2. Explore and Understand Data
    3. Data preparation and preprocessing 
    4. Modeling

#### 1. Collect Inspection Data

After importing the necessary libraries, we download the data from the HM Land Registry website as follows:

In [1]:
import os # Operating System
import numpy as np
import pandas as pd
import datetime as dt # Datetime
import json # library to handle JSON files

!conda install -c conda-forge geopy --yes
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

!conda install -c conda-forge folium=0.5.0 --yes
import folium #import folium # map rendering library

print('Libraries imported.')

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.4.5.1         |   py36h9f0ad1d_0         151 KB  conda-forge
    geographiclib-1.50         |             py_0          34 KB  conda-forge
    openssl-1.1.1g             |       h516909a_0         2.1 MB  conda-forge
    geopy-1.22.0               |     pyh9f0ad1d_0          63 KB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following NEW packages will be INSTALLED:

    geographiclib:   1.50-py_0           conda-forge
    geopy:           1.22.0-pyh9f0ad1d_0 conda-forge
    python_abi:      3.6-1_cp36m         conda-forge

The following packages will be UPDATED:

    ca-certificates: 2020.1.1-0                      --> 2020.4.5.1-hecc5488_0     conda-forge
    certifi:         2020.4.5.1-py36_0               --> 2020.4.5.1-py36h9f0ad1d_0 conda-forge
    openssl:         1.1.1g-h7b6447c_0               --> 1.1.1g-h516909a_0         conda-forge


Downloading and Extracting Packages
certifi-2020.4.5.1   | 151 KB    | ##################################### | 100%
geographiclib-1.50   | 34 KB     | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
geopy-1.22.0         | 63 KB     | ##################################### | 100%
python_abi-3.6       | 4 KB      | ##################################### | 100%
ca-certificates-2020 | 146 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    branca-0.4.1               |             py_0          26 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         713 KB

The following NEW packages will be INSTALLED:

    altair:  4.1.0-py_1 conda-forge
    branca:  0.4.1-py_0 conda-forge
    folium:  0.5.0-py_0 conda-forge
    vincent: 0.4.4-py_1 conda-forge


Downloading and Extracting Packages
vincent-0.4.4        | 28 KB     | ##################################### | 100%
branca-0.4.1         | 26 KB     | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Libraries imported.

In [2]:
#Read the data for examination (Source: http://landregistry.data.gov.uk/)
df_ppd = pd.read_csv("http://prod2.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-2018.csv")

Before using data, we will have to explore and understand it.

#### 2. Explore and Understand Data

We read the dataset that we collected from the HM Land Registry website into a pandas' data frame and display the first five rows of it as follows:

In [3]:
df_ppd.head(5)

,{666758D7-43A9-3363-E053-6B04A8C0D74E},405000,2018-01-25 00:00,WR15 8LH,D,N,F,RAMBLERS WAY,Unnamed: 8,Unnamed: 9,BORASTON,TENBURY WELLS,SHROPSHIRE,SHROPSHIRE.1,A,A.1
0,{666758D7-43AA-3363-E053-6B04A8C0D74E},315000,2018-01-23 00:00,SY7 8QA,D,N,F,MONT CENISE,NaN,NaN,CLUN,CRAVEN ARMS,SHROPSHIRE,SHROPSHIRE,A,A
1,{666758D7-43AD-3363-E053-6B04A8C0D74E},165000,2018-01-19 00:00,SY1 2BF,T,Y,F,42,NaN,PENSON WAY,NaN,SHREWSBURY,SHROPSHIRE,SHROPSHIRE,A,A
2,{666758D7-43B0-3363-E053-6B04A8C0D74E},370000,2018-01-22 00:00,SY8 4DF,D,N,F,WILLOW HEY,NaN,NaN,ASHFORD CARBONEL,LUDLOW,SHROPSHIRE,SHROPSHIRE,A,A
3,{666758D7-43B3-3363-E053-6B04A8C0D74E},320000,2018-01-19 00:00,TF10 7ET,D,N,F,3,NaN,PRINCESS GARDENS,NaN,NEWPORT,WREKIN,WREKIN,A,A
4,{666758D7-43B4-3363-E053-6B04A8C0D74E},180000,2018-01-31 00:00,SY3 0NQ,S,N,F,79,NaN,LYTHWOOD ROAD,BAYSTON HILL,SHREWSBURY,SHROPSHIRE,SHROPSHIRE,A,A

In [4]:
df_ppd.shape

(1029799, 16)

Our dataset consists of over 700000 rows and 16 columns. We will now prepare and preprocess data accordingly.

#### 3. Data preparation and preprocessing

At this stage, we prepare our dataset for the modeling process, opting for the most suitable machine learning algorithm for our scope. Accordingly, we perform the following steps: 
- Rename the column names 
- Format the date column 
- Sort data by date of sale 
- Select data only for the city of London 
- Make a list of street names in London 
- Calculate the street-wise average price of the property
- Read the street-wise coordinates into a data frame, eliminating recurring word London from individual names 
- Join the data to find the coordinates of locations which fit into client's budget
- Plot recommended locations on London map along with current market prices

In [5]:
# Assign meaningful column names
df_ppd.columns = ['TUID', 'Price', 'Date_Transfer', 'Postcode', 'Prop_Type', 'Old_New', 'Duration', 'PAON', \
                  'SAON', 'Street', 'Locality', 'Town_City', 'District', 'County', 'PPD_Cat_Type', 'Record_Status']

In [6]:
# Format the date column
df_ppd['Date_Transfer'] = df_ppd['Date_Transfer'].apply(pd.to_datetime)

# Delete all obsolete transactions which were done before 2016
df_ppd.drop(df_ppd[df_ppd.Date_Transfer.dt.year < 2016].index, inplace=True)

# Sort by Date of Sale
df_ppd.sort_values(by=['Date_Transfer'],ascending=[False],inplace=True)

In [7]:
df_ppd_london = df_ppd.query("Town_City == 'LONDON'")

# Make a list of street names in LONDON
streets = df_ppd_london['Street'].unique().tolist()

In [8]:
df_grp_price = df_ppd_london.groupby(['Street'])['Price'].mean().reset_index()

# Give meaningful names to the columns
df_grp_price.columns = ['Street', 'Avg_Price']

In [9]:
#Input your Budget's Upper Limit and Lower Limit - Find the locations df_grp_price which fits your budget
df_affordable = df_grp_price.query("(Avg_Price >= 2200000) & (Avg_Price <= 2500000)")

In [10]:
# Display the dataframe
df_affordable

                      Street     Avg_Price
196            ALBION SQUARE  2.450000e+06
390              ANHALT ROAD  2.435000e+06
405          ANSDELL TERRACE  2.250000e+06
422          APPLEGARTH ROAD  2.400000e+06
855          BARONSMEAD ROAD  2.375000e+06
981           BEAUCLERC ROAD  2.480000e+06
1102         BELVEDERE DRIVE  2.340000e+06
1215       BICKENHALL STREET  2.208500e+06
1253       BIRCHLANDS AVENUE  2.217000e+06
1553          BRAMPTON GROVE  2.456875e+06
1632       BRIARDALE GARDENS  2.397132e+06
1797                BROOKWAY  2.400000e+06
1914            BURBAGE ROAD  2.445000e+06
1980               BURY WALK  2.492500e+06
2068         CALLCOTT STREET  2.375000e+06
2129       CAMPDEN HILL ROAD  2.379653e+06
2136            CAMPION ROAD  2.461000e+06
2158           CANNING PLACE  2.425000e+06
2225           CARLISLE ROAD  2.200000e+06
2230         CARLTON GARDENS  2.483500e+06
2242           CARLYLE COURT  2.300000e+06
2406          CHALCOT SQUARE  2.286679e+06
2484            CHARLES LANE  2.414000e+06
2562        CHELSEA CRESCENT  2.495000e+06
2606     CHESTER CLOSE NORTH  2.450000e+06
2638            CHEYNE COURT  2.250000e+06
2641              CHEYNE ROW  2.410000e+06
2686           CHISWICK MALL  2.287500e+06
2761               CITY ROAD  2.468340e+06
2808        CLARENDON STREET  2.250000e+06
...                      ...           ...
10935   RUSSELL GARDENS MEWS  2.300000e+06
11182         SETTLES STREET  2.487500e+06
11257         SHELDON AVENUE  2.349542e+06
11491          SOUTH END ROW  2.470000e+06
11568    SOUTHWOOD LAWN ROAD  2.350000e+06
11571         SOVEREIGN PARK  2.500000e+06
11788  ST MARGARETS CRESCENT  2.216500e+06
11824       ST OSWALDS PLACE  2.250000e+06
11844       ST PETERS SQUARE  2.468730e+06
11881       STAFFORD TERRACE  2.355000e+06
12221       SUTHERLAND PLACE  2.456000e+06
12283          SYDNEY STREET  2.240833e+06
12425            THAMES BANK  2.400000e+06
12487            THE HEXAGON  2.335000e+06
12766        TREDEGAR SQUARE  2.436666e+06
12828         TRINITY STREET  2.317500e+06
12978   UPPER HAMPSTEAD WALK  2.500000e+06
13240        WALPOLE GARDENS  2.303500e+06
13242         WALPOLE STREET  2.242500e+06
13316         WARWICK SQUARE  2.432273e+06
13415            WELBECK WAY  2.267000e+06
13427      WELLESLEY TERRACE  2.410000e+06
13438      WELLINGTON STREET  2.293155e+06
13570     WESTMORELAND PLACE  2.300000e+06
13677       WHITFIELD STREET  2.451000e+06
13722         WILFRED STREET  2.410538e+06
13748     WILLOW BRIDGE ROAD  2.425000e+06
13768          WILSON STREET  2.257500e+06
13796        WINCHENDON ROAD  2.350000e+06
13833           WINGATE ROAD  2.206400e+06

[162 rows x 2 columns]

In [11]:
import pandas as pd
import numpy as np
import datetime as DT
import hmac
from geopy.geocoders import Nominatim
from geopy.distance import vincenty
# import k-means from clustering stage
from sklearn.cluster import KMeans

In [12]:
for index, item in df_affordable.iterrows():
    print(f"index: {index}")
    print(f"item: {item}")
    print(f"item.Street only: {item.Street}")

index: 196
item: Street       ALBION SQUARE
Avg_Price         2.45e+06
Name: 196, dtype: object
item.Street only: ALBION SQUARE
index: 390
item: Street       ANHALT ROAD
Avg_Price      2.435e+06
Name: 390, dtype: object
item.Street only: ANHALT ROAD
index: 405
item: Street       ANSDELL TERRACE
Avg_Price           2.25e+06
Name: 405, dtype: object
item.Street only: ANSDELL TERRACE
index: 422
item: Street       APPLEGARTH ROAD
Avg_Price            2.4e+06
Name: 422, dtype: object
item.Street only: APPLEGARTH ROAD
index: 855
item: Street       BARONSMEAD ROAD
Avg_Price          2.375e+06
Name: 855, dtype: object
item.Street only: BARONSMEAD ROAD
index: 981
item: Street       BEAUCLERC ROAD
Avg_Price          2.48e+06
Name: 981, dtype: object
item.Street only: BEAUCLERC ROAD
index: 1102
item: Street       BELVEDERE DRIVE
Avg_Price           2.34e+06
Name: 1102, dtype: object
item.Street only: BELVEDERE DRIVE
index: 1215
item: Street       BICKENHALL STREET
Avg_Price           2.2085e+06
Name: 1215, dtype: object
item.Street only: BICKENHALL STREET
index: 1253
item: Street       BIRCHLANDS AVENUE
Avg_Price            2.217e+06
Name: 1253, dtype: object
item.Street only: BIRCHLANDS AVENUE
index: 1553
item: Street       BRAMPTON GROVE
Avg_Price       2.45688e+06
Name: 1553, dtype: object
item.Street only: BRAMPTON GROVE
index: 1632
item: Street       BRIARDALE GARDENS
Avg_Price          2.39713e+06
Name: 1632, dtype: object
item.Street only: BRIARDALE GARDENS
index: 1797
item: Street       BROOKWAY
Avg_Price     2.4e+06
Name: 1797, dtype: object
item.Street only: BROOKWAY
index: 1914
item: Street       BURBAGE ROAD
Avg_Price       2.445e+06
Name: 1914, dtype: object
item.Street only: BURBAGE ROAD
index: 1980
item: Street        BURY WALK
Avg_Price    2.4925e+06
Name: 1980, dtype: object
item.Street only: BURY WALK
index: 2068
item: Street       CALLCOTT STREET
Avg_Price          2.375e+06
Name: 2068, dtype: object
item.Street only: CALLCOTT STREET
index: 2129
item: Street       CAMPDEN HILL ROAD
Avg_Price          2.37965e+06
Name: 2129, dtype: object
item.Street only: CAMPDEN HILL ROAD
index: 2136
item: Street       CAMPION ROAD
Avg_Price       2.461e+06
Name: 2136, dtype: object
item.Street only: CAMPION ROAD
index: 2158
item: Street       CANNING PLACE
Avg_Price        2.425e+06
Name: 2158, dtype: object
item.Street only: CANNING PLACE
index: 2225
item: Street       CARLISLE ROAD
Avg_Price          2.2e+06
Name: 2225, dtype: object
item.Street only: CARLISLE ROAD
index: 2230
item: Street       CARLTON GARDENS
Avg_Price         2.4835e+06
Name: 2230, dtype: object
item.Street only: CARLTON GARDENS
index: 2242
item: Street       CARLYLE COURT
Avg_Price          2.3e+06
Name: 2242, dtype: object
item.Street only: CARLYLE COURT
index: 2406
item: Street       CHALCOT SQUARE
Avg_Price       2.28668e+06
Name: 2406, dtype: object
item.Street only: CHALCOT SQUARE
index: 2484
item: Street       CHARLES LANE
Avg_Price       2.414e+06
Name: 2484, dtype: object
item.Street only: CHARLES LANE
index: 2562
item: Street       CHELSEA CRESCENT
Avg_Price           2.495e+06
Name: 2562, dtype: object
item.Street only: CHELSEA CRESCENT
index: 2606
item: Street       CHESTER CLOSE NORTH
Avg_Price               2.45e+06
Name: 2606, dtype: object
item.Street only: CHESTER CLOSE NORTH
index: 2638
item: Street       CHEYNE COURT
Avg_Price        2.25e+06
Name: 2638, dtype: object
item.Street only: CHEYNE COURT
index: 2641
item: Street       CHEYNE ROW
Avg_Price      2.41e+06
Name: 2641, dtype: object
item.Street only: CHEYNE ROW
index: 2686
item: Street       CHISWICK MALL
Avg_Price       2.2875e+06
Name: 2686, dtype: object
item.Street only: CHISWICK MALL
index: 2761
item: Street         CITY ROAD
Avg_Price    2.46834e+06
Name: 2761, dtype: object
item.Street only: CITY ROAD
index: 2808
item: Street       CLARENDON STREET
Avg_Price            2.25e+06
Name: 2808, dtype: object
item.Street only: CLARENDON STREET
index: 2900
item: Street       CLONCURRY STREET
Avg_Price         2.38833e+06
Name: 2900, dtype: object
item.Street only: CLONCURRY STREET
index: 2944
item: Street       COLBECK MEWS
Avg_Price      2.3675e+06
Name: 2944, dtype: object
item.Street only: COLBECK MEWS
index: 2995
item: Street       COLLEGE CRESCENT
Avg_Price            2.44e+06
Name: 2995, dtype: object
item.Street only: COLLEGE CRESCENT
index: 3202
item: Street       CORNWALL TERRACE MEWS
Avg_Price                 2.35e+06
Name: 3202, dtype: object
item.Street only: CORNWALL TERRACE MEWS
index: 3255
item: Street       COURT LANE GARDENS
Avg_Price              2.36e+06
Name: 3255, dtype: object
item.Street only: COURT LANE GARDENS
index: 3377
item: Street       CRESCENT GROVE
Avg_Price         2.298e+06
Name: 3377, dtype: object
item.Street only: CRESCENT GROVE
index: 3583
item: Street       DALEBURY ROAD
Avg_Price          2.4e+06
Name: 3583, dtype: object
item.Street only: DALEBURY ROAD
index: 3848
item: Street       DEWHURST ROAD
Avg_Price        2.425e+06
Name: 3848, dtype: object
item.Street only: DEWHURST ROAD
index: 3929
item: Street       DORIA ROAD
Avg_Price    2.3625e+06
Name: 3929, dtype: object
item.Street only: DORIA ROAD
index: 3980
item: Street       DOWNSHIRE HILL
Avg_Price         2.225e+06
Name: 3980, dtype: object
item.Street only: DOWNSHIRE HILL
index: 4035
item: Street       DUCHESS WALK
Avg_Price      2.4775e+06
Name: 4035, dtype: object
item.Street only: DUCHESS WALK
index: 4232
item: Street       ECCLESTON SQUARE MEWS
Avg_Price               2.3355e+06
Name: 4232, dtype: object
item.Street only: ECCLESTON SQUARE MEWS
index: 4285
item: Street       EGBERT STREET
Avg_Price        2.265e+06
Name: 4285, dtype: object
item.Street only: EGBERT STREET
index: 4289
item: Street       EGERTON PLACE
Avg_Price          2.2e+06
Name: 4289, dtype: object
item.Street only: EGERTON PLACE
index: 4375
item: Street       ELM PARK ROAD
Avg_Price      2.32042e+06
Name: 4375, dtype: object
item.Street only: ELM PARK ROAD
index: 4894
item: Street       FLORAL STREET
Avg_Price      2.22722e+06
Name: 4894, dtype: object
item.Street only: FLORAL STREET
index: 5016
item: Street       FRANK DIXON WAY
Avg_Price         2.2125e+06
Name: 5016, dtype: object
item.Street only: FRANK DIXON WAY
index: 5098
item: Street       FULTON MEWS
Avg_Price      2.299e+06
Name: 5098, dtype: object
item.Street only: FULTON MEWS
index: 5241
item: Street       GERARD ROAD
Avg_Price     2.2585e+06
Name: 5241, dtype: object
item.Street only: GERARD ROAD
index: 5244
item: Street       GERRARD ROAD
Avg_Price      2.2425e+06
Name: 5244, dtype: object
item.Street only: GERRARD ROAD
index: 5289
item: Street       GIRDLERS ROAD
Avg_Price      2.44167e+06
Name: 5289, dtype: object
item.Street only: GIRDLERS ROAD
index: 5382
item: Street       GLOUCESTER CRESCENT
Avg_Price            2.35083e+06
Name: 5382, dtype: object
item.Street only: GLOUCESTER CRESCENT
index: 5450
item: Street       GORDON PLACE
Avg_Price       2.477e+06
Name: 5450, dtype: object
item.Street only: GORDON PLACE
index: 5486
item: Street       GRAFTON SQUARE
Avg_Price          2.27e+06
Name: 5486, dtype: object
item.Street only: GRAFTON SQUARE
index: 5493
item: Street       GRAHAM TERRACE
Avg_Price         2.325e+06
Name: 5493, dtype: object
item.Street only: GRAHAM TERRACE
index: 5952
item: Street       HARMAN DRIVE
Avg_Price      2.2625e+06
Name: 5952, dtype: object
item.Street only: HARMAN DRIVE
index: 5976
item: Street       HARRIS STREET
Avg_Price      2.47177e+06
Name: 5976, dtype: object
item.Street only: HARRIS STREET
index: 6039
item: Street       HAVANNAH STREET
Avg_Price        2.21731e+06
Name: 6039, dtype: object
item.Street only: HAVANNAH STREET
index: 6111
item: Street       HAZLEWELL ROAD
Avg_Price           2.5e+06
Name: 6111, dtype: object
item.Street only: HAZLEWELL ROAD
index: 6227
item: Street       HEREFORD MEWS
Avg_Price         2.31e+06
Name: 6227, dtype: object
item.Street only: HEREFORD MEWS
index: 6247
item: Street       HERONDALE AVENUE
Avg_Price           2.475e+06
Name: 6247, dtype: object
item.Street only: HERONDALE AVENUE
index: 6344
item: Street       HIGHGATE HIGH STREET
Avg_Price               2.211e+06
Name: 6344, dtype: object
item.Street only: HIGHGATE HIGH STREET
index: 6359
item: Street       HIGHWOOD HILL
Avg_Price       2.2525e+06
Name: 6359, dtype: object
item.Street only: HIGHWOOD HILL
index: 6395
item: Street       HILLGATE PLACE
Avg_Price           2.2e+06
Name: 6395, dtype: object
item.Street only: HILLGATE PLACE
index: 6506
item: Street       HOLLYCROFT AVENUE
Avg_Price          2.36138e+06
Name: 6506, dtype: object
item.Street only: HOLLYCROFT AVENUE
index: 6510
item: Street       HOLLYWOOD MEWS
Avg_Price          2.35e+06
Name: 6510, dtype: object
item.Street only: HOLLYWOOD MEWS
index: 6555
item: Street       HONEYWELL ROAD
Avg_Price       2.27833e+06
Name: 6555, dtype: object
item.Street only: HONEYWELL ROAD
index: 6611
item: Street       HORTENSIA ROAD
Avg_Price       2.27592e+06
Name: 6611, dtype: object
item.Street only: HORTENSIA ROAD
index: 6640
item: Street       HOXTON SQUARE
Avg_Price      2.23429e+06
Name: 6640, dtype: object
item.Street only: HOXTON SQUARE
index: 6666
item: Street       HUNTER ROAD
Avg_Price        2.3e+06
Name: 6666, dtype: object
item.Street only: HUNTER ROAD
index: 6825
item: Street       JACKSONS LANE
Avg_Price       2.3625e+06
Name: 6825, dtype: object
item.Street only: JACKSONS LANE
index: 6885
item: Street       JOHN STREET
Avg_Price      2.235e+06
Name: 6885, dtype: object
item.Street only: JOHN STREET
index: 7190
item: Street       KINNERTON STREET
Avg_Price          2.4856e+06
Name: 7190, dtype: object
item.Street only: KINNERTON STREET
index: 7224
item: Street       KNARESBOROUGH PLACE
Avg_Price              2.325e+06
Name: 7224, dtype: object
item.Street only: KNARESBOROUGH PLACE
index: 7244
item: Street       KNOX STREET
Avg_Price       2.25e+06
Name: 7244, dtype: object
item.Street only: KNOX STREET
index: 7264
item: Street       LADBROKE GROVE
Avg_Price        2.4833e+06
Name: 7264, dtype: object
item.Street only: LADBROKE GROVE
index: 7333
item: Street       LANCASTER MEWS
Avg_Price        2.3125e+06
Name: 7333, dtype: object
item.Street only: LANCASTER MEWS
index: 7403
item: Street       LANSDOWNE ROAD
Avg_Price       2.36488e+06
Name: 7403, dtype: object
item.Street only: LANSDOWNE ROAD
index: 7432
item: Street       LATIMER INDUSTRIAL ESTATE
Avg_Price                      2.4e+06
Name: 7432, dtype: object
item.Street only: LATIMER INDUSTRIAL ESTATE
index: 7485
item: Street       LAXTON PLACE
Avg_Price         2.5e+06
Name: 7485, dtype: object
item.Street only: LAXTON PLACE
index: 7687
item: Street       LINCOLN AVENUE
Avg_Price        2.2035e+06
Name: 7687, dtype: object
item.Street only: LINCOLN AVENUE
index: 7716
item: Street       LINGFIELD ROAD
Avg_Price       2.24875e+06
Name: 7716, dtype: object
item.Street only: LINGFIELD ROAD
index: 7745
item: Street       LISSON STREET
Avg_Price       2.4625e+06
Name: 7745, dtype: object
item.Street only: LISSON STREET
index: 7779
item: Street       LIVERPOOL GROVE
Avg_Price          2.288e+06
Name: 7779, dtype: object
item.Street only: LIVERPOOL GROVE
index: 7871
item: Street       LONGWOOD DRIVE
Avg_Price         2.375e+06
Name: 7871, dtype: object
item.Street only: LONGWOOD DRIVE
index: 7877
item: Street       LONSDALE SQUARE
Avg_Price         2.3575e+06
Name: 7877, dtype: object
item.Street only: LONSDALE SQUARE
index: 8415
item: Street       MAZE HILL
Avg_Price     2.25e+06
Name: 8415, dtype: object
item.Street only: MAZE HILL
index: 8550
item: Street       MIDDLESEX PASSAGE
Avg_Price             2.28e+06
Name: 8550, dtype: object
item.Street only: MIDDLESEX PASSAGE
index: 8714
item: Street       MONTPELIER AVENUE
Avg_Price              2.5e+06
Name: 8714, dtype: object
item.Street only: MONTPELIER AVENUE
index: 8724
item: Street       MONTPELIER WALK
Avg_Price           2.32e+06
Name: 8724, dtype: object
item.Street only: MONTPELIER WALK
index: 8872
item: Street       MULTON ROAD
Avg_Price        2.3e+06
Name: 8872, dtype: object
item.Street only: MULTON ROAD
index: 8877
item: Street       MUNDEN STREET
Avg_Price         2.25e+06
Name: 8877, dtype: object
item.Street only: MUNDEN STREET
index: 9151
item: Street       NORFOLK CRESCENT
Avg_Price         2.22333e+06
Name: 9151, dtype: object
item.Street only: NORFOLK CRESCENT
index: 9174
item: Street       NORTH CIRCULAR ROAD
Avg_Price            2.39314e+06
Name: 9174, dtype: object
item.Street only: NORTH CIRCULAR ROAD
index: 9250
item: Street       NOTTINGHAM STREET
Avg_Price           2.2275e+06
Name: 9250, dtype: object
item.Street only: NOTTINGHAM STREET
index: 9325
item: Street       OAKLEY STREET
Avg_Price      2.38129e+06
Name: 9325, dtype: object
item.Street only: OAKLEY STREET
index: 9336
item: Street       OAKWOOD COURT
Avg_Price      2.34875e+06
Name: 9336, dtype: object
item.Street only: OAKWOOD COURT
index: 9344
item: Street       OBSERVATORY GARDENS
Avg_Price               2.42e+06
Name: 9344, dtype: object
item.Street only: OBSERVATORY GARDENS
index: 9379
item: Street       OLD COURT PLACE
Avg_Price          2.395e+06
Name: 9379, dtype: object
item.Street only: OLD COURT PLACE
index: 9440
item: Street       ONSLOW MEWS WEST
Avg_Price             2.3e+06
Name: 9440, dtype: object
item.Street only: ONSLOW MEWS WEST
index: 9572
item: Street       PALACE PLACE
Avg_Price         2.3e+06
Name: 9572, dtype: object
item.Street only: PALACE PLACE
index: 9601
item: Street       PANTON STREET
Avg_Price        2.475e+06
Name: 9601, dtype: object
item.Street only: PANTON STREET
index: 9620
item: Street       PARK CRESCENT
Avg_Price         2.44e+06
Name: 9620, dtype: object
item.Street only: PARK CRESCENT
index: 9629
item: Street        PARK LANE
Avg_Price    2.2415e+06
Name: 9629, dtype: object
item.Street only: PARK LANE
index: 9650
item: Street       PARKE ROAD
Avg_Price    2.2625e+06
Name: 9650, dtype: object
item.Street only: PARKE ROAD
index: 9653
item: Street       PARKFIELDS
Avg_Price       2.2e+06
Name: 9653, dtype: object
item.Street only: PARKFIELDS
index: 9690
item: Street       PARTHENIA ROAD
Avg_Price       2.20057e+06
Name: 9690, dtype: object
item.Street only: PARTHENIA ROAD
index: 9722
item: Street       PAVILION ROAD
Avg_Price          2.2e+06
Name: 9722, dtype: object
item.Street only: PAVILION ROAD
index: 9783
item: Street       PEMBRIDGE MEWS
Avg_Price         2.251e+06
Name: 9783, dtype: object
item.Street only: PEMBRIDGE MEWS
index: 9785
item: Street       PEMBRIDGE ROAD
Avg_Price           2.4e+06
Name: 9785, dtype: object
item.Street only: PEMBRIDGE ROAD
index: 9794
item: Street       PEMBROKE STUDIOS
Avg_Price            2.45e+06
Name: 9794, dtype: object
item.Street only: PEMBROKE STUDIOS
index: 9799
item: Street       PENCOMBE MEWS
Avg_Price          2.2e+06
Name: 9799, dtype: object
item.Street only: PENCOMBE MEWS
index: 9879
item: Street       PETERSHAM PLACE
Avg_Price            2.3e+06
Name: 9879, dtype: object
item.Street only: PETERSHAM PLACE
index: 9894
item: Street       PHILLIMORE GARDENS
Avg_Price           2.48467e+06
Name: 9894, dtype: object
item.Street only: PHILLIMORE GARDENS
index: 9902
item: Street       PHYSIC PLACE
Avg_Price         2.5e+06
Name: 9902, dtype: object
item.Street only: PHYSIC PLACE
index: 9940
item: Street       PITFIELD STREET
Avg_Price        2.48333e+06
Name: 9940, dtype: object
item.Street only: PITFIELD STREET
index: 10150
item: Street       PRINCES GATE
Avg_Price     2.40333e+06
Name: 10150, dtype: object
item.Street only: PRINCES GATE
index: 10178
item: Street       PRIORY ROAD
Avg_Price    2.24826e+06
Name: 10178, dtype: object
item.Street only: PRIORY ROAD
index: 10189
item: Street       PROTHERO GARDENS
Avg_Price          2.2025e+06
Name: 10189, dtype: object
item.Street only: PROTHERO GARDENS
index: 10225
item: Street       PUTNEY HIGH STREET
Avg_Price            2.3486e+06
Name: 10225, dtype: object
item.Street only: PUTNEY HIGH STREET
index: 10242
item: Street       QUARRENDON STREET
Avg_Price          2.43775e+06
Name: 10242, dtype: object
item.Street only: QUARRENDON STREET
index: 10275
item: Street       QUEENS GATE TERRACE
Avg_Price            2.39944e+06
Name: 10275, dtype: object
item.Street only: QUEENS GATE TERRACE
index: 10329
item: Street       RADSTOCK STREET
Avg_Price         2.2175e+06
Name: 10329, dtype: object
item.Street only: RADSTOCK STREET
index: 10374
item: Street       RANELAGH AVENUE
Avg_Price            2.3e+06
Name: 10374, dtype: object
item.Street only: RANELAGH AVENUE
index: 10482
item: Street       REDCLIFFE ROAD
Avg_Price       2.44875e+06
Name: 10482, dtype: object
item.Street only: REDCLIFFE ROAD
index: 10507
item: Street       REEVES MEWS
Avg_Price       2.45e+06
Name: 10507, dtype: object
item.Street only: REEVES MEWS
index: 10564
item: Street       RHEIDOL MEWS
Avg_Price        2.31e+06
Name: 10564, dtype: object
item.Street only: RHEIDOL MEWS
index: 10619
item: Street       RINGWOOD AVENUE
Avg_Price          2.275e+06
Name: 10619, dtype: object
item.Street only: RINGWOOD AVENUE
index: 10700
item: Street       RODERICK ROAD
Avg_Price          2.4e+06
Name: 10700, dtype: object
item.Street only: RODERICK ROAD
index: 10757
item: Street       ROPEMAKERS FIELDS
Avg_Price              2.5e+06
Name: 10757, dtype: object
item.Street only: ROPEMAKERS FIELDS
index: 10872
item: Street       ROYAL CRESCENT
Avg_Price       2.34833e+06
Name: 10872, dtype: object
item.Street only: ROYAL CRESCENT
index: 10878
item: Street       ROYAL HILL
Avg_Price    2.2525e+06
Name: 10878, dtype: object
item.Street only: ROYAL HILL
index: 10935
item: Street       RUSSELL GARDENS MEWS
Avg_Price                 2.3e+06
Name: 10935, dtype: object
item.Street only: RUSSELL GARDENS MEWS
index: 11182
item: Street       SETTLES STREET
Avg_Price        2.4875e+06
Name: 11182, dtype: object
item.Street only: SETTLES STREET
index: 11257
item: Street       SHELDON AVENUE
Avg_Price       2.34954e+06
Name: 11257, dtype: object
item.Street only: SHELDON AVENUE
index: 11491
item: Street       SOUTH END ROW
Avg_Price         2.47e+06
Name: 11491, dtype: object
item.Street only: SOUTH END ROW
index: 11568
item: Street       SOUTHWOOD LAWN ROAD
Avg_Price               2.35e+06
Name: 11568, dtype: object
item.Street only: SOUTHWOOD LAWN ROAD
index: 11571
item: Street       SOVEREIGN PARK
Avg_Price           2.5e+06
Name: 11571, dtype: object
item.Street only: SOVEREIGN PARK
index: 11788
item: Street       ST MARGARETS CRESCENT
Avg_Price               2.2165e+06
Name: 11788, dtype: object
item.Street only: ST MARGARETS CRESCENT
index: 11824
item: Street       ST OSWALDS PLACE
Avg_Price            2.25e+06
Name: 11824, dtype: object
item.Street only: ST OSWALDS PLACE
index: 11844
item: Street       ST PETERS SQUARE
Avg_Price         2.46873e+06
Name: 11844, dtype: object
item.Street only: ST PETERS SQUARE
index: 11881
item: Street       STAFFORD TERRACE
Avg_Price           2.355e+06
Name: 11881, dtype: object
item.Street only: STAFFORD TERRACE
index: 12221
item: Street       SUTHERLAND PLACE
Avg_Price           2.456e+06
Name: 12221, dtype: object
item.Street only: SUTHERLAND PLACE
index: 12283
item: Street       SYDNEY STREET
Avg_Price      2.24083e+06
Name: 12283, dtype: object
item.Street only: SYDNEY STREET
index: 12425
item: Street       THAMES BANK
Avg_Price        2.4e+06
Name: 12425, dtype: object
item.Street only: THAMES BANK
index: 12487
item: Street       THE HEXAGON
Avg_Price      2.335e+06
Name: 12487, dtype: object
item.Street only: THE HEXAGON
index: 12766
item: Street       TREDEGAR SQUARE
Avg_Price        2.43667e+06
Name: 12766, dtype: object
item.Street only: TREDEGAR SQUARE
index: 12828
item: Street       TRINITY STREET
Avg_Price        2.3175e+06
Name: 12828, dtype: object
item.Street only: TRINITY STREET
index: 12978
item: Street       UPPER HAMPSTEAD WALK
Avg_Price                 2.5e+06
Name: 12978, dtype: object
item.Street only: UPPER HAMPSTEAD WALK

In [13]:
geolocator = Nominatim()

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: Using Nominatim with the default "geopy/1.22.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  if __name__ == '__main__':

In [14]:
df_affordable['city_coord'] = df_affordable['Street'].apply(geolocator.geocode).apply(lambda x: (x.latitude, x.longitude))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [15]:
df_affordable

,Street,Avg_Price,city_coord
196,ALBION SQUARE,2.450000e+06,"(-41.27375755, 173.28939323910353)"
390,ANHALT ROAD,2.435000e+06,"(51.4803164, -0.1668011)"
405,ANSDELL TERRACE,2.250000e+06,"(51.4998899, -0.1891027)"
422,APPLEGARTH ROAD,2.400000e+06,"(53.7486539, -0.3266704)"
855,BARONSMEAD ROAD,2.375000e+06,"(51.4773147, -0.239457)"
981,BEAUCLERC ROAD,2.480000e+06,"(30.2114523, -81.6179807)"
1102,BELVEDERE DRIVE,2.340000e+06,"(38.0728178, -78.4587964)"
1215,BICKENHALL STREET,2.208500e+06,"(51.5212014, -0.1589082)"
1253,BIRCHLANDS AVENUE,2.217000e+06,"(51.4483941, -0.1604676)"
1553,BRAMPTON GROVE,2.456875e+06,"(51.5899607, -0.3185249)"
1632,BRIARDALE GARDENS,2.397132e+06,"(51.5601748, -0.1954305)"
1797,BROOKWAY,2.400000e+06,"(45.432184899999996, -122.80281166115779)"
1914,BURBAGE ROAD,2.445000e+06,"(52.5385071, -1.3536736)"
1980,BURY WALK,2.492500e+06,"(52.1455294, -0.4235933)"
2068,CALLCOTT STREET,2.375000e+06,"(51.5083499, -0.1983276)"
2129,CAMPDEN HILL ROAD,2.379653e+06,"(51.5081106, -0.1996673)"
2136,CAMPION ROAD,2.461000e+06,"(43.623321, -70.236225)"
2158,CANNING PLACE,2.425000e+06,"(52.6410267, -1.135223)"
2225,CARLISLE ROAD,2.200000e+06,"(43.3994382, -79.973215)"
2230,CARLTON GARDENS,2.483500e+06,"(-37.80194335, 144.9719701710172)"
2242,CARLYLE COURT,2.300000e+06,"(32.972700950000004, -97.17339170977195)"
2406,CHALCOT SQUARE,2.286679e+06,"(51.5410876, -0.1559279)"
2484,CHARLES LANE,2.414000e+06,"(40.257626, -75.093891)"
2562,CHELSEA CRESCENT,2.495000e+06,"(34.522443, -85.443891)"
2606,CHESTER CLOSE NORTH,2.450000e+06,"(51.5292054, -0.1450813)"
2638,CHEYNE COURT,2.250000e+06,"(52.0359049, 0.7276119)"
2641,CHEYNE ROW,2.410000e+06,"(51.4837173, -0.169603)"
2686,CHISWICK MALL,2.287500e+06,"(51.4879942, -0.2466045)"
2761,CITY ROAD,2.468340e+06,"(51.5296972, -0.0977626)"
2808,CLARENDON STREET,2.250000e+06,"(42.2849611, -71.3455345)"
...,...,...,...
10935,RUSSELL GARDENS MEWS,2.300000e+06,"(51.4999175, -0.2119443)"
11182,SETTLES STREET,2.487500e+06,"(32.2394242, -101.4571232)"
11257,SHELDON AVENUE,2.349542e+06,"(42.0209245, -93.6542243)"
11491,SOUTH END ROW,2.470000e+06,"(51.4987463, -0.1890787)"
11568,SOUTHWOOD LAWN ROAD,2.350000e+06,"(51.5746267, -0.146238)"
11571,SOVEREIGN PARK,2.500000e+06,"(-27.49371345, 153.21014259876813)"
11788,ST MARGARETS CRESCENT,2.216500e+06,"(17.0975135, -88.6161153)"
11824,ST OSWALDS PLACE,2.250000e+06,"(51.4872071, -0.1185341)"
11844,ST PETERS SQUARE,2.468730e+06,"(41.9022353, 12.457357310298008)"
11881,STAFFORD TERRACE,2.355000e+06,"(53.680501, -1.5183383)"
12221,SUTHERLAND PLACE,2.456000e+06,"(51.8711375, -0.4228998)"
12283,SYDNEY STREET,2.240833e+06,"(-29.823972, 30.9192479)"
12425,THAMES BANK,2.400000e+06,"(52.0856689, -0.2432764)"
12487,THE HEXAGON,2.335000e+06,"(51.45388235, -0.9778342181052991)"
12766,TREDEGAR SQUARE,2.436666e+06,"(51.5270935, -0.03218423325966063)"
12828,TRINITY STREET,2.317500e+06,"(50.3383163, -4.7954295)"
12978,UPPER HAMPSTEAD WALK,2.500000e+06,"(51.558467, -0.1774529)"
13240,WALPOLE GARDENS,2.303500e+06,"(51.4397435, -0.3412634)"
13242,WALPOLE STREET,2.242500e+06,"(-27.8725844, 151.2717768)"
13316,WARWICK SQUARE,2.432273e+06,"(33.7385632, -117.84650567746482)"
13415,WELBECK WAY,2.267000e+06,"(52.5580053, -0.262309)"
13427,WELLESLEY TERRACE,2.410000e+06,"(54.9743127, -1.6402018)"
13438,WELLINGTON STREET,2.293155e+06,"(45.4234495, -75.6980579)"
13570,WESTMORELAND PLACE,2.300000e+06,"(40.7402242, -111.8463235)"
13677,WHITFIELD STREET,2.451000e+06,"(-12.4607263, 130.8395852)"
13722,WILFRED STREET,2.410538e+06,"(51.442178, 0.372743)"
13748,WILLOW BRIDGE ROAD,2.425000e+06,"(53.6408743, -1.2004617)"
13768,WILSON STREET,2.257500e+06,"(42.766462, -71.099469)"
13796,WINCHENDON ROAD,2.350000e+06,"(42.645331, -71.954714)"
13833,WINGATE ROAD,2.206400e+06,"(51.092557, 1.1794554)"

In [16]:
df_affordable[['Latitude', 'Longitude']] = df_affordable['city_coord'].apply(pd.Series)

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/core/frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [17]:
df_affordable

,Street,Avg_Price,city_coord,Latitude,Longitude
196,ALBION SQUARE,2.450000e+06,"(-41.27375755, 173.28939323910353)",-41.273758,173.289393
390,ANHALT ROAD,2.435000e+06,"(51.4803164, -0.1668011)",51.480316,-0.166801
405,ANSDELL TERRACE,2.250000e+06,"(51.4998899, -0.1891027)",51.499890,-0.189103
422,APPLEGARTH ROAD,2.400000e+06,"(53.7486539, -0.3266704)",53.748654,-0.326670
855,BARONSMEAD ROAD,2.375000e+06,"(51.4773147, -0.239457)",51.477315,-0.239457
981,BEAUCLERC ROAD,2.480000e+06,"(30.2114523, -81.6179807)",30.211452,-81.617981
1102,BELVEDERE DRIVE,2.340000e+06,"(38.0728178, -78.4587964)",38.072818,-78.458796
1215,BICKENHALL STREET,2.208500e+06,"(51.5212014, -0.1589082)",51.521201,-0.158908
1253,BIRCHLANDS AVENUE,2.217000e+06,"(51.4483941, -0.1604676)",51.448394,-0.160468
1553,BRAMPTON GROVE,2.456875e+06,"(51.5899607, -0.3185249)",51.589961,-0.318525
1632,BRIARDALE GARDENS,2.397132e+06,"(51.5601748, -0.1954305)",51.560175,-0.195431
1797,BROOKWAY,2.400000e+06,"(45.432184899999996, -122.80281166115779)",45.432185,-122.802812
1914,BURBAGE ROAD,2.445000e+06,"(52.5385071, -1.3536736)",52.538507,-1.353674
1980,BURY WALK,2.492500e+06,"(52.1455294, -0.4235933)",52.145529,-0.423593
2068,CALLCOTT STREET,2.375000e+06,"(51.5083499, -0.1983276)",51.508350,-0.198328
2129,CAMPDEN HILL ROAD,2.379653e+06,"(51.5081106, -0.1996673)",51.508111,-0.199667
2136,CAMPION ROAD,2.461000e+06,"(43.623321, -70.236225)",43.623321,-70.236225
2158,CANNING PLACE,2.425000e+06,"(52.6410267, -1.135223)",52.641027,-1.135223
2225,CARLISLE ROAD,2.200000e+06,"(43.3994382, -79.973215)",43.399438,-79.973215
2230,CARLTON GARDENS,2.483500e+06,"(-37.80194335, 144.9719701710172)",-37.801943,144.971970
2242,CARLYLE COURT,2.300000e+06,"(32.972700950000004, -97.17339170977195)",32.972701,-97.173392
2406,CHALCOT SQUARE,2.286679e+06,"(51.5410876, -0.1559279)",51.541088,-0.155928
2484,CHARLES LANE,2.414000e+06,"(40.257626, -75.093891)",40.257626,-75.093891
2562,CHELSEA CRESCENT,2.495000e+06,"(34.522443, -85.443891)",34.522443,-85.443891
2606,CHESTER CLOSE NORTH,2.450000e+06,"(51.5292054, -0.1450813)",51.529205,-0.145081
2638,CHEYNE COURT,2.250000e+06,"(52.0359049, 0.7276119)",52.035905,0.727612
2641,CHEYNE ROW,2.410000e+06,"(51.4837173, -0.169603)",51.483717,-0.169603
2686,CHISWICK MALL,2.287500e+06,"(51.4879942, -0.2466045)",51.487994,-0.246605
2761,CITY ROAD,2.468340e+06,"(51.5296972, -0.0977626)",51.529697,-0.097763
2808,CLARENDON STREET,2.250000e+06,"(42.2849611, -71.3455345)",42.284961,-71.345534
...,...,...,...,...,...
10935,RUSSELL GARDENS MEWS,2.300000e+06,"(51.4999175, -0.2119443)",51.499918,-0.211944
11182,SETTLES STREET,2.487500e+06,"(32.2394242, -101.4571232)",32.239424,-101.457123
11257,SHELDON AVENUE,2.349542e+06,"(42.0209245, -93.6542243)",42.020924,-93.654224
11491,SOUTH END ROW,2.470000e+06,"(51.4987463, -0.1890787)",51.498746,-0.189079
11568,SOUTHWOOD LAWN ROAD,2.350000e+06,"(51.5746267, -0.146238)",51.574627,-0.146238
11571,SOVEREIGN PARK,2.500000e+06,"(-27.49371345, 153.21014259876813)",-27.493713,153.210143
11788,ST MARGARETS CRESCENT,2.216500e+06,"(17.0975135, -88.6161153)",17.097514,-88.616115
11824,ST OSWALDS PLACE,2.250000e+06,"(51.4872071, -0.1185341)",51.487207,-0.118534
11844,ST PETERS SQUARE,2.468730e+06,"(41.9022353, 12.457357310298008)",41.902235,12.457357
11881,STAFFORD TERRACE,2.355000e+06,"(53.680501, -1.5183383)",53.680501,-1.518338
12221,SUTHERLAND PLACE,2.456000e+06,"(51.8711375, -0.4228998)",51.871138,-0.422900
12283,SYDNEY STREET,2.240833e+06,"(-29.823972, 30.9192479)",-29.823972,30.919248
12425,THAMES BANK,2.400000e+06,"(52.0856689, -0.2432764)",52.085669,-0.243276
12487,THE HEXAGON,2.335000e+06,"(51.45388235, -0.9778342181052991)",51.453882,-0.977834
12766,TREDEGAR SQUARE,2.436666e+06,"(51.5270935, -0.03218423325966063)",51.527093,-0.032184
12828,TRINITY STREET,2.317500e+06,"(50.3383163, -4.7954295)",50.338316,-4.795430
12978,UPPER HAMPSTEAD WALK,2.500000e+06,"(51.558467, -0.1774529)",51.558467,-0.177453
13240,WALPOLE GARDENS,2.303500e+06,"(51.4397435, -0.3412634)",51.439743,-0.341263
13242,WALPOLE STREET,2.242500e+06,"(-27.8725844, 151.2717768)",-27.872584,151.271777
13316,WARWICK SQUARE,2.432273e+06,"(33.7385632, -117.84650567746482)",33.738563,-117.846506
13415,WELBECK WAY,2.267000e+06,"(52.5580053, -0.262309)",52.558005,-0.262309
13427,WELLESLEY TERRACE,2.410000e+06,"(54.9743127, -1.6402018)",54.974313,-1.640202
13438,WELLINGTON STREET,2.293155e+06,"(45.4234495, -75.6980579)",45.423449,-75.698058
13570,WESTMORELAND PLACE,2.300000e+06,"(40.7402242, -111.8463235)",40.740224,-111.846323
13677,WHITFIELD STREET,2.451000e+06,"(-12.4607263, 130.8395852)",-12.460726,130.839585
13722,WILFRED STREET,2.410538e+06,"(51.442178, 0.372743)",51.442178,0.372743
13748,WILLOW BRIDGE ROAD,2.425000e+06,"(53.6408743, -1.2004617)",53.640874,-1.200462
13768,WILSON STREET,2.257500e+06,"(42.766462, -71.099469)",42.766462,-71.099469
13796,WINCHENDON ROAD,2.350000e+06,"(42.645331, -71.954714)",42.645331,-71.954714
13833,WINGATE ROAD,2.206400e+06,"(51.092557, 1.1794554)",51.092557,1.179455

In [18]:
df = df_affordable.drop(columns=['city_coord'])

In [19]:
df

                      Street     Avg_Price   Latitude   Longitude
196            ALBION SQUARE  2.450000e+06 -41.273758  173.289393
390              ANHALT ROAD  2.435000e+06  51.480316   -0.166801
405          ANSDELL TERRACE  2.250000e+06  51.499890   -0.189103
422          APPLEGARTH ROAD  2.400000e+06  53.748654   -0.326670
855          BARONSMEAD ROAD  2.375000e+06  51.477315   -0.239457
981           BEAUCLERC ROAD  2.480000e+06  30.211452  -81.617981
1102         BELVEDERE DRIVE  2.340000e+06  38.072818  -78.458796
1215       BICKENHALL STREET  2.208500e+06  51.521201   -0.158908
1253       BIRCHLANDS AVENUE  2.217000e+06  51.448394   -0.160468
1553          BRAMPTON GROVE  2.456875e+06  51.589961   -0.318525
1632       BRIARDALE GARDENS  2.397132e+06  51.560175   -0.195431
1797                BROOKWAY  2.400000e+06  45.432185 -122.802812
1914            BURBAGE ROAD  2.445000e+06  52.538507   -1.353674
1980               BURY WALK  2.492500e+06  52.145529   -0.423593
2068         CALLCOTT STREET  2.375000e+06  51.508350   -0.198328
2129       CAMPDEN HILL ROAD  2.379653e+06  51.508111   -0.199667
2136            CAMPION ROAD  2.461000e+06  43.623321  -70.236225
2158           CANNING PLACE  2.425000e+06  52.641027   -1.135223
2225           CARLISLE ROAD  2.200000e+06  43.399438  -79.973215
2230         CARLTON GARDENS  2.483500e+06 -37.801943  144.971970
2242           CARLYLE COURT  2.300000e+06  32.972701  -97.173392
2406          CHALCOT SQUARE  2.286679e+06  51.541088   -0.155928
2484            CHARLES LANE  2.414000e+06  40.257626  -75.093891
2562        CHELSEA CRESCENT  2.495000e+06  34.522443  -85.443891
2606     CHESTER CLOSE NORTH  2.450000e+06  51.529205   -0.145081
2638            CHEYNE COURT  2.250000e+06  52.035905    0.727612
2641              CHEYNE ROW  2.410000e+06  51.483717   -0.169603
2686           CHISWICK MALL  2.287500e+06  51.487994   -0.246605
2761               CITY ROAD  2.468340e+06  51.529697   -0.097763
2808        CLARENDON STREET  2.250000e+06  42.284961  -71.345534
...                      ...           ...        ...         ...
10935   RUSSELL GARDENS MEWS  2.300000e+06  51.499918   -0.211944
11182         SETTLES STREET  2.487500e+06  32.239424 -101.457123
11257         SHELDON AVENUE  2.349542e+06  42.020924  -93.654224
11491          SOUTH END ROW  2.470000e+06  51.498746   -0.189079
11568    SOUTHWOOD LAWN ROAD  2.350000e+06  51.574627   -0.146238
11571         SOVEREIGN PARK  2.500000e+06 -27.493713  153.210143
11788  ST MARGARETS CRESCENT  2.216500e+06  17.097514  -88.616115
11824       ST OSWALDS PLACE  2.250000e+06  51.487207   -0.118534
11844       ST PETERS SQUARE  2.468730e+06  41.902235   12.457357
11881       STAFFORD TERRACE  2.355000e+06  53.680501   -1.518338
12221       SUTHERLAND PLACE  2.456000e+06  51.871138   -0.422900
12283          SYDNEY STREET  2.240833e+06 -29.823972   30.919248
12425            THAMES BANK  2.400000e+06  52.085669   -0.243276
12487            THE HEXAGON  2.335000e+06  51.453882   -0.977834
12766        TREDEGAR SQUARE  2.436666e+06  51.527093   -0.032184
12828         TRINITY STREET  2.317500e+06  50.338316   -4.795430
12978   UPPER HAMPSTEAD WALK  2.500000e+06  51.558467   -0.177453
13240        WALPOLE GARDENS  2.303500e+06  51.439743   -0.341263
13242         WALPOLE STREET  2.242500e+06 -27.872584  151.271777
13316         WARWICK SQUARE  2.432273e+06  33.738563 -117.846506
13415            WELBECK WAY  2.267000e+06  52.558005   -0.262309
13427      WELLESLEY TERRACE  2.410000e+06  54.974313   -1.640202
13438      WELLINGTON STREET  2.293155e+06  45.423449  -75.698058
13570     WESTMORELAND PLACE  2.300000e+06  40.740224 -111.846323
13677       WHITFIELD STREET  2.451000e+06 -12.460726  130.839585
13722         WILFRED STREET  2.410538e+06  51.442178    0.372743
13748     WILLOW BRIDGE ROAD  2.425000e+06  53.640874   -1.200462
13768          WILSON STREET  2.257500e+06  42.766462  -71.099469
13796        WINCHENDON ROAD  2.350000e+06  42.645331  -71.954714
13833           WINGATE ROAD  2.206400e+06  51.092557    1.179455

[162 rows x 4 columns]

In [20]:
address = 'London, UK'

geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of London City are {}, {}.'.format(latitude, longitude))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: DeprecationWarning: Using Nominatim with the default "geopy/1.22.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  app.launch_new_instance()

The geograpical coordinate of London City are 51.5073219, -0.1276474.